name: rotate

on:
  workflow_dispatch: 

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
        apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        apt-get update
        apt-get install terraform=0.14.10
    - run: |
        terraform --version
